import type { CareerPath } from '../types'

// Demo/example paths only. Production recommendation logic will be added in a future phase.
export const careerPaths: CareerPath[] = [
  { id: 'product-operations', title: 'Product Operations', description: 'Help product teams stay organized, informed, and focused on improving how products are built.', matchScore: 86, fitReasons: ['Strong coordination experience', 'Transferable project management skills', 'Communication strengths'], developSkills: ['Product analytics', 'Product tools', 'Industry knowledge'], roleOverview: 'Product Operations connects people, process, and information so product teams can do their best work. You might improve planning routines, document customer insights, or help teams make decisions with clearer data.', entryPoints: ['Operations Coordinator', 'Product Operations Associate', 'Business Operations Associate'] },
  { id: 'project-management', title: 'Project Management', description: 'Guide people, timelines, and priorities from an idea through to delivery.', matchScore: 82, fitReasons: ['Organization and follow-through', 'Clear communication', 'Experience balancing priorities'], developSkills: ['Project tools', 'Risk management', 'Formal delivery methods'], roleOverview: 'Project managers bring clarity to work that involves several people or moving parts. The role usually includes planning work, keeping stakeholders informed, and helping teams solve obstacles before they grow.', entryPoints: ['Project Coordinator', 'Junior Project Manager', 'Program Assistant'] },
  { id: 'business-operations', title: 'Business Operations', description: 'Make everyday business processes clearer, smoother, and more effective.', matchScore: 78, fitReasons: ['Practical problem solving', 'Cross-team communication', 'Process awareness'], developSkills: ['Operational metrics', 'Business systems', 'Process mapping'], roleOverview: 'Business Operations focuses on the practical systems that help an organization run well. It can involve improving workflows, coordinating teams, and turning day-to-day information into better decisions.', entryPoints: ['Operations Coordinator', 'Business Operations Associate', 'Administrative Operations Specialist'] },
  { id: 'data-analysis', title: 'Data Analysis', description: 'Turn information into clear findings that help people make better decisions.', matchScore: 74, fitReasons: ['Analytical thinking', 'Attention to detail', 'Ability to communicate findings'], developSkills: ['Excel or SQL', 'Data visualization', 'Statistical foundations'], roleOverview: 'Data analysts look for useful patterns in information and explain what those patterns mean. The work can include organizing data, answering business questions, and presenting findings in a clear, practical way.', entryPoints: ['Data Analyst Intern', 'Reporting Analyst', 'Operations Data Coordinator'] },
  { id: 'digital-marketing', title: 'Digital Marketing', description: 'Help organizations reach and understand audiences through online channels.', matchScore: 71, fitReasons: ['Communication skills', 'Audience awareness', 'Project coordination'], developSkills: ['Marketing platforms', 'Campaign analysis', 'Content strategy'], roleOverview: 'Digital marketing combines clear communication with thoughtful experimentation. Depending on the role, you may help plan campaigns, create content, understand audiences, or evaluate what is working.', entryPoints: ['Marketing Coordinator', 'Digital Marketing Assistant', 'Content Operations Associate'] },
]

export const findCareerPath = (id?: string): CareerPath => careerPaths.find((path) => path.id === id) ?? careerPaths[0]!
