import { useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import { Badge, Button, Card, ProgressBar } from '../components/ui'
import { useAppStore } from '../store/useAppStore'

export function CareerAnalysisPage() {
  const { userProfile, onboardingAnswers } = useAppStore()
  const [isAnalyzing, setIsAnalyzing] = useState(true)
  useEffect(() => { const timer = window.setTimeout(() => setIsAnalyzing(false), 1500); return () => window.clearTimeout(timer) }, [])
  const skillCount = onboardingAnswers.technicalSkills.length + onboardingAnswers.professionalSkills.length
  const experienceYears = userProfile.yearsOfExperience ?? (onboardingAnswers.experiences.length ? onboardingAnswers.experiences.length * 2 : 0)
  const strengths = onboardingAnswers.professionalSkills.slice(0, 3).length ? onboardingAnswers.professionalSkills.slice(0, 3) : ['Adaptability', 'Communication', 'Problem solving']
  const transferable = onboardingAnswers.technicalSkills.slice(0, 3).length ? onboardingAnswers.technicalSkills.slice(0, 3) : ['Organization', 'Stakeholder communication', 'Project coordination']
  if (isAnalyzing) return <div className="mx-auto flex min-h-[60vh] max-w-xl items-center px-5 text-center sm:px-6"><div className="w-full"><span className="mx-auto mb-6 grid size-14 place-items-center rounded-full bg-primary-100 text-2xl text-primary-700" aria-hidden="true">↗</span><p className="text-sm font-semibold uppercase tracking-[0.16em] text-secondary-600">Career analysis</p><h1 className="mt-3 font-display text-4xl font-semibold tracking-tight text-primary-800">We&apos;re looking at your experience, skills and goals...</h1><p className="mt-4 text-neutral-700">Bringing together the details you shared to create a practical starting point.</p><div className="mt-8"><ProgressBar value={72} label="Preparing your profile" /></div><span className="sr-only" role="status">Preparing your career profile</span></div></div>
  return <div className="mx-auto max-w-5xl px-5 py-12 sm:px-6"><section className="max-w-2xl"><p className="text-sm font-semibold uppercase tracking-[0.16em] text-secondary-600">Career analysis</p><h1 className="mt-2 font-display text-5xl font-semibold tracking-tight text-primary-800">Your Career Profile</h1><p className="mt-4 text-lg text-neutral-700">This is an encouraging starting point, not a prediction. Use it to notice the experience you already bring and decide what to explore next.</p></section><div className="mt-10 grid gap-4 sm:grid-cols-3"><Stat value={`${experienceYears || 'Your'} ${experienceYears ? 'years' : 'experience'}`} label="professional experience" /><Stat value={`${skillCount || 'Several'} ${skillCount ? 'identified' : 'emerging'}`} label="skills" /><Stat value={`${strengths.length} transferable`} label="strengths" /></div><div className="mt-10 grid gap-5 lg:grid-cols-3"><ProfileSection title="Your Strengths" intro="The qualities that can support you across roles and industries." items={strengths} tone="success" /><ProfileSection title="Your Transferable Skills" intro="Experience can carry forward even when the job title changes." items={transferable} tone="primary" /><ProfileSection title="Areas to Develop" intro="Focused learning can help make a transition more achievable." items={['Role-specific tools', 'Current industry knowledge', 'Confidence telling your career story']} tone="warning" /></div><div className="mt-10 text-center"><Link to="/career-discovery"><Button>Explore Career Directions</Button></Link></div></div>
}

function Stat({ value, label }: { value: string; label: string }) { return <Card className="p-5 shadow-none"><p className="font-display text-3xl font-semibold text-primary-800">{value}</p><p className="mt-1 text-sm text-neutral-700">{label}</p></Card> }
function ProfileSection({ title, intro, items, tone }: { title: string; intro: string; items: string[]; tone: 'success' | 'primary' | 'warning' }) { const styles = { success: 'bg-success-50 text-success-700', primary: 'bg-primary-50 text-primary-700', warning: 'bg-warning-50 text-warning-700' }; return <Card className="p-6 shadow-none"><h2 className="font-display text-2xl font-semibold text-primary-800">{title}</h2><p className="mt-2 text-sm leading-6 text-neutral-700">{intro}</p><div className="mt-5 flex flex-wrap gap-2">{items.map((item) => <Badge key={item} className={styles[tone]}>{item}</Badge>)}</div></Card> }
