import { useEffect } from 'react'
import { Link, useParams } from 'react-router-dom'
import { Button, Card } from '../components/ui'
import { findCareerPath } from '../mock-data/careerPaths'
import { useAppStore } from '../store/useAppStore'

export function CareerDetailPage() {
  const { careerId } = useParams()
  const { onboardingAnswers, selectedCareerPath, setSelectedCareerPath } = useAppStore()
  const path = selectedCareerPath?.id === careerId && selectedCareerPath ? selectedCareerPath : findCareerPath(careerId)
  useEffect(() => { if (selectedCareerPath?.id !== path.id) setSelectedCareerPath(path) }, [path, selectedCareerPath?.id, setSelectedCareerPath])
  const existingSkills = [...onboardingAnswers.technicalSkills, ...onboardingAnswers.professionalSkills].slice(0, 3)
  const skillsYouHave = existingSkills.length ? existingSkills : ['Communication', 'Project coordination', 'Team management']
  return <div className="mx-auto max-w-5xl px-5 py-12 sm:px-6"><Link to="/career-discovery" className="text-sm font-semibold text-primary-700 hover:text-primary-800">← All career directions</Link><section className="mt-8 max-w-3xl"><p className="text-sm font-semibold uppercase tracking-[0.16em] text-secondary-600">Potential career path</p><h1 className="mt-2 font-display text-5xl font-semibold tracking-tight text-primary-800">{path.title}</h1><p className="mt-4 text-lg text-neutral-700">{path.description}</p></section><div className="mt-10 grid gap-5 lg:grid-cols-2"><Card><h2 className="font-display text-2xl font-semibold text-primary-800">What this role involves</h2><p className="mt-3 leading-7 text-neutral-700">{path.roleOverview}</p></Card><Card><h2 className="font-display text-2xl font-semibold text-primary-800">Why it could fit you</h2><p className="mt-3 text-neutral-700">Your profile suggests strengths that can be useful here:</p><ul className="mt-4 space-y-2 text-neutral-700">{path.fitReasons?.map((reason) => <li key={reason}>✓ {reason}</li>)}</ul></Card><Card><h2 className="font-display text-2xl font-semibold text-primary-800">Skills you already have</h2><ul className="mt-4 space-y-2 text-neutral-700">{skillsYouHave.map((skill) => <li key={skill} className="flex gap-2"><span className="font-semibold text-success-700">✓</span>{skill}</li>)}</ul></Card><Card><h2 className="font-display text-2xl font-semibold text-primary-800">Skills you may need to develop</h2><ul className="mt-4 space-y-2 text-neutral-700">{path.developSkills?.map((skill) => <li key={skill} className="flex gap-2"><span className="font-semibold text-warning-700">○</span>{skill}</li>)}</ul></Card></div><Card className="mt-5"><h2 className="font-display text-2xl font-semibold text-primary-800">Possible entry points</h2><p className="mt-2 text-neutral-700">Roles that can offer a practical way to begin building relevant experience.</p><div className="mt-4 flex flex-wrap gap-2">{path.entryPoints?.map((role) => <span key={role} className="rounded-full bg-primary-50 px-3 py-1.5 text-sm font-medium text-primary-700">{role}</span>)}</div></Card><div className="mt-10 text-center"><Link to="/roadmap"><Button>Build My Career Roadmap</Button></Link></div></div>
}
