import { useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { Button, Card } from '../components/ui'
import { careerPaths } from '../mock-data/careerPaths'
import { useAppStore } from '../store/useAppStore'

export function CareerDiscoveryPage() {
  const navigate = useNavigate()
  const { setSelectedCareerPath } = useAppStore()
  const [showWhy, setShowWhy] = useState(false)
  const explore = (id: string) => { const path = careerPaths.find((item) => item.id === id)!; setSelectedCareerPath(path); navigate(`/career/${path.id}`) }
  return <div className="mx-auto max-w-6xl px-5 py-12 sm:px-6"><section className="max-w-2xl"><p className="text-sm font-semibold uppercase tracking-[0.16em] text-secondary-600">Career discovery</p><h1 className="mt-2 font-display text-5xl font-semibold tracking-tight text-primary-800">Where could you go from here?</h1><p className="mt-4 text-lg text-neutral-700">These directions are examples to explore, based on the strengths, preferences, and goals you shared. They are not guaranteed outcomes.</p></section><div className="mt-8 rounded-card border border-neutral-200 bg-neutral-100 px-5 py-4"><button type="button" className="flex w-full items-center justify-between text-left font-semibold text-primary-800" aria-expanded={showWhy} onClick={() => setShowWhy((shown) => !shown)}>Why am I seeing these recommendations?<span aria-hidden="true">{showWhy ? '−' : '+'}</span></button>{showWhy && <p className="mt-3 max-w-3xl text-sm leading-6 text-neutral-700">We considered the skills and experience you described, what you want next, and the work conditions that matter to you. Recommendations are intended as practical starting points for exploration, not as a definitive assessment.</p>}</div><div className="mt-8 grid gap-5 md:grid-cols-2 xl:grid-cols-3">{careerPaths.map((path) => <Card key={path.id} className="flex flex-col p-6"><div className="flex items-start justify-between gap-4"><h2 className="font-display text-2xl font-semibold text-primary-800">{path.title}</h2><span className="shrink-0 rounded-full bg-primary-50 px-2.5 py-1 text-xs font-semibold text-primary-700">{path.matchScore}% potential fit</span></div><p className="mt-3 text-sm leading-6 text-neutral-700">{path.description}</p><div className="mt-5"><p className="text-xs font-semibold uppercase tracking-wide text-neutral-500">Why it may fit</p><ul className="mt-2 space-y-1 text-sm text-neutral-700">{path.fitReasons?.map((reason) => <li key={reason}>• {reason}</li>)}</ul></div><div className="mt-4"><p className="text-xs font-semibold uppercase tracking-wide text-neutral-500">Skills to develop</p><p className="mt-2 text-sm text-neutral-700">{path.developSkills?.join(' · ')}</p></div><Button className="mt-6 w-full" onClick={() => explore(path.id)}>Explore This Path</Button></Card>)}</div></div>
}
