import { Link } from 'react-router-dom'
import { Button, Card, ProgressBar } from '../components/ui'
import { roadmapProgress } from '../lib/careerProgress'
import { findCareerPath } from '../mock-data/careerPaths'
import { useAppStore } from '../store/useAppStore'

export function RoadmapPage() {
  const { selectedCareerPath, roadmapTasks, toggleRoadmapTask } = useAppStore()
  const path = selectedCareerPath ?? findCareerPath()
  const progress = roadmapProgress(roadmapTasks)
  const stages = [...new Set(roadmapTasks.map((task) => task.stage))]
  return <div className="mx-auto max-w-5xl px-5 py-12 sm:px-6"><section className="max-w-3xl"><p className="text-sm font-semibold uppercase tracking-[0.16em] text-secondary-600">{path.title} pathway</p><h1 className="mt-2 font-display text-5xl font-semibold tracking-tight text-primary-800">Your Career Comeback Roadmap.</h1><p className="mt-4 text-lg text-neutral-700">A focused eight-week plan designed to make steady progress feel manageable, not overwhelming.</p></section><Card className="mt-8 border-primary-100 bg-primary-50 p-6 shadow-none"><div className="flex flex-wrap items-baseline justify-between gap-2"><h2 className="font-display text-2xl font-semibold text-primary-800">Your overall progress</h2><span className="text-lg font-semibold text-primary-700">{progress}% complete</span></div><div className="mt-4"><ProgressBar value={progress} /></div><p className="mt-3 text-sm text-neutral-700">Every small completed task counts. Adjust your pace when life needs more room.</p></Card><div className="mt-10 space-y-6">{stages.map((stage, index) => { const tasks = roadmapTasks.filter((task) => task.stage === stage); return <section key={stage} className="grid gap-4 md:grid-cols-[120px_1fr]"><div className="pt-2"><p className="text-sm font-semibold text-secondary-600">{tasks[0]?.weeks}</p><span className="mt-2 grid size-8 place-items-center rounded-full bg-primary-700 text-sm font-semibold text-white">{index + 1}</span></div><Card className="p-5 sm:p-6"><h2 className="font-display text-2xl font-semibold text-primary-800">{stage}</h2><div className="mt-5 divide-y divide-neutral-200">{tasks.map((task) => <div key={task.id} className="flex items-start gap-3 py-4 first:pt-0 last:pb-0"><input className="mt-1 size-5 shrink-0 cursor-pointer accent-primary-700" type="checkbox" checked={task.completed} onChange={() => toggleRoadmapTask(task.id)} aria-label={`Mark ${task.title} as ${task.completed ? 'incomplete' : 'complete'}`} /><div className="min-w-0 flex-1"><p className={`font-medium ${task.completed ? 'text-neutral-500 line-through' : 'text-neutral-900'}`}>{task.title}</p><p className="mt-1 text-sm text-neutral-700">Estimated time: {task.estimatedTime}</p></div>{task.aiAssistance && <Link to="/ai-coach"><Button variant="ghost" className="h-auto min-h-0 shrink-0 px-2 py-1 text-xs">AI assistance</Button></Link>}</div>)}</div></Card></section> })}</div></div>
}
