import { useState } from 'react'
import { Link } from 'react-router-dom'
import { Badge, Card, ProgressBar } from '../components/ui'
import { findCareerPath } from '../mock-data/careerPaths'
import { useAppStore } from '../store/useAppStore'

type SkillStatus = 'Strong' | 'Developing' | 'Needs Development'
type SkillItem = { name: string; category: string; status: SkillStatus; level: number; target: number; why: string; improvement: string }

export function SkillsPage() {
  const { onboardingAnswers, selectedCareerPath, roadmapTasks } = useAppStore()
  const path = selectedCareerPath ?? findCareerPath()
  const [selected, setSelected] = useState<SkillItem | null>(null)
  const current = [...onboardingAnswers.technicalSkills.map((name) => ({ name, category: 'Technical skills' })), ...onboardingAnswers.professionalSkills.map((name) => ({ name, category: 'Professional skills' }))]
  const currentSkills = current.length ? current : [{ name: 'Communication', category: 'Professional skills' }, { name: 'Project coordination', category: 'Professional skills' }, { name: 'Organization', category: 'Professional skills' }]
  const skills: SkillItem[] = [...currentSkills.map(({ name, category }, index) => ({ name, category, status: index === 0 ? 'Strong' as const : 'Developing' as const, level: index === 0 ? 78 : 58, target: 80, why: `${name} supports clear, reliable work in ${path.title} roles.`, improvement: `Use a small, practical task to show how you apply ${name}.` })), ...(path.developSkills ?? []).filter((name) => !currentSkills.some((skill) => skill.name.toLowerCase() === name.toLowerCase())).map((name) => ({ name, category: 'Target career skills', status: 'Needs Development' as const, level: 20, target: 75, why: `${name} is commonly useful when moving into ${path.title}.`, improvement: `Start with an introductory activity, then use it in a small practice project.` }))]
  const groups = [...new Set(skills.map((skill) => skill.category))]
  const relatedTask = selected && roadmapTasks.find((task) => task.targetSkill?.toLowerCase() === selected.name.toLowerCase())
  return <div className="mx-auto max-w-6xl px-5 py-12 sm:px-6"><section className="max-w-2xl"><p className="text-sm font-semibold uppercase tracking-[0.16em] text-secondary-600">Skills profile</p><h1 className="mt-2 font-display text-5xl font-semibold tracking-tight text-primary-800">Your Current Skills</h1><p className="mt-4 text-lg text-neutral-700">A practical view of what you already bring and what may help you move toward {path.title}.</p></section><div className="mt-9 grid gap-6 lg:grid-cols-[1fr_0.9fr]"><div className="space-y-5">{groups.map((group) => <Card key={group} className="p-6"><h2 className="font-display text-2xl font-semibold text-primary-800">{group}</h2><div className="mt-4 space-y-3">{skills.filter((skill) => skill.category === group).map((skill) => <button key={skill.name} type="button" onClick={() => setSelected(skill)} className="flex w-full items-center justify-between rounded-control border border-neutral-200 px-4 py-3 text-left hover:border-primary-500 hover:bg-primary-50"><span className="font-medium text-neutral-900">{skill.name}</span><Status status={skill.status} /></button>)}</div></Card>)}</div><div><Card className="p-6"><h2 className="font-display text-2xl font-semibold text-primary-800">Skills for Your Target Career</h2><p className="mt-2 text-sm text-neutral-700">Current confidence compared with a helpful target for {path.title}.</p><div className="mt-6 space-y-5">{skills.slice(0, 5).map((skill) => <div key={skill.name}><div className="flex justify-between gap-4 text-sm"><span className="font-medium text-neutral-900">{skill.name}</span><span className="text-neutral-700">{skill.level}% → {skill.target}%</span></div><div className="mt-2"><ProgressBar value={skill.level} /></div></div>)}</div></Card>{selected && <Card className="mt-5 border-primary-100 bg-primary-50 p-6"><h2 className="font-display text-2xl font-semibold text-primary-800">{selected.name}</h2><dl className="mt-4 space-y-4 text-sm"><div><dt className="font-semibold text-neutral-900">Why it matters</dt><dd className="mt-1 text-neutral-700">{selected.why}</dd></div><div><dt className="font-semibold text-neutral-900">Current level</dt><dd className="mt-1 text-neutral-700">{selected.status} ({selected.level}%)</dd></div><div><dt className="font-semibold text-neutral-900">A useful next step</dt><dd className="mt-1 text-neutral-700">{selected.improvement}</dd></div></dl>{relatedTask && <Link className="mt-5 inline-block text-sm font-semibold text-primary-700 hover:text-primary-800" to="/roadmap">Related roadmap task: {relatedTask.title} →</Link>}</Card>}</div></div></div>
}

function Status({ status }: { status: SkillStatus }) { const tone = status === 'Strong' ? 'success' : status === 'Developing' ? 'neutral' : 'warning'; return <Badge tone={tone}>{status}</Badge> }
